// <auto-generated />
using Arkhos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arkhos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arkhos.Core.Models.CityInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<int>("AreaTerritorial")
                        .HasColumnType("int")
                        .HasColumnName("area_territorial");

                    b.Property<double>("DensidadeDemografica")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("densidade_demografica");

                    b.Property<int>("IdMesorregiao")
                        .HasColumnType("int")
                        .HasColumnName("id_mesorregiao");

                    b.Property<int>("IdMicrorregiao")
                        .HasColumnType("int")
                        .HasColumnName("id_microrregiao");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int")
                        .HasColumnName("municipio_id");

                    b.Property<string>("NomeMesorregiao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_mesorregiao");

                    b.Property<string>("NomeMicrorregiao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_microrregiao");

                    b.Property<string>("NomeMunicipio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_municipio");

                    b.Property<int>("PopulacaoTotal")
                        .HasColumnType("int")
                        .HasColumnName("populacao_total");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId", "Ano");

                    b.ToTable("city_info", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolEnrollDict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tamanho");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Variavel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variavel");

                    b.HasKey("Id");

                    b.ToTable("school_enroll_dict", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolEnrollValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<int>("AtributoId")
                        .HasColumnType("int")
                        .HasColumnName("id_atributo");

                    b.Property<int>("IdEscolaEnrollValues")
                        .HasColumnType("int")
                        .HasColumnName("id_escola_fk");

                    b.Property<string>("TipoAtributo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_atributo");

                    b.Property<double>("Valor")
                        .HasColumnType("numeric(10,1)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("IdEscolaEnrollValues", "Ano");

                    b.ToTable("school_enroll_values", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Alocacao")
                        .HasColumnType("smallint")
                        .HasColumnName("alocacao");

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<int>("CityInfoId")
                        .HasColumnType("int")
                        .HasColumnName("id_municipio_fk");

                    b.Property<short>("Dependencia")
                        .HasColumnType("smallint")
                        .HasColumnName("dependencia");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<short>("Funcionamento")
                        .HasColumnType("smallint")
                        .HasColumnName("funcionamento");

                    b.Property<int>("IdEscola")
                        .HasColumnType("int")
                        .HasColumnName("escola_id");

                    b.Property<double?>("Lat")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("lat");

                    b.Property<short?>("Localizacao")
                        .HasColumnType("smallint");

                    b.Property<double?>("Lon")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("lon");

                    b.Property<string>("NomeEscola")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_escola");

                    b.Property<short>("Ocupacao")
                        .HasColumnType("smallint")
                        .HasColumnName("ocupacao");

                    b.Property<int?>("Sede")
                        .HasColumnType("int")
                        .HasColumnName("sede");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Ano");

                    b.HasIndex("CityInfoId", "Ano");

                    b.HasIndex("IdEscola", "Ano");

                    b.ToTable("school_info", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfraDict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tamanho");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Variavel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variavel");

                    b.HasKey("Id");

                    b.ToTable("school_infra_dict", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfraValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<int>("AtributoId")
                        .HasColumnType("int")
                        .HasColumnName("id_atributo");

                    b.Property<int>("IdEscolaInfraValues")
                        .HasColumnType("int")
                        .HasColumnName("id_escola_fk");

                    b.Property<string>("TipoAtributo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_atributo");

                    b.Property<double>("Valor")
                        .HasColumnType("numeric(10,1)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("AtributoId");

                    b.HasIndex("IdEscolaInfraValues", "Ano");

                    b.ToTable("school_infra_values", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1L, null, null, null, null, null);

                    b.Property<double>("AcessibilityRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("acessibility_rating");

                    b.Property<double>("AdministrativeBurdenRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("administrative_burden_rating");

                    b.Property<double>("AgeGradeDistortionRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("age_grade_distortion_rating");

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<double?>("ApprovalRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("approval_rate");

                    b.Property<double?>("DropoutRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("dropout_rate");

                    b.Property<double?>("FailureRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("failure_rate");

                    b.Property<double>("HumanSupportRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("human_support_rating");

                    b.Property<double?>("IdebRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("ideb_rating");

                    b.Property<double>("InfrastructureSpendingPerStudent")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("infrastructure_spending_per_student");

                    b.Property<double>("ManagementRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("management_rating");

                    b.Property<double>("MealSpendingPerStudent")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("meal_spending_per_student");

                    b.Property<double>("PedagogicalRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("pedagogical_rating");

                    b.Property<double>("PedagogicalSpendingPerStudent")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("pedagogical_spending_per_student");

                    b.Property<double>("RecreationRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("recreation_rating");

                    b.Property<double?>("SaebRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("saeb_rating");

                    b.Property<int>("SchoolInfoId")
                        .HasColumnType("int")
                        .HasColumnName("id_escola_fk");

                    b.Property<double>("SpendingPerStudent")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("spending_per_student");

                    b.Property<double>("SpendingPerTeacher")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("spending_per_teacher");

                    b.Property<double>("TeacherInstabilityRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("teacher_instability_rating");

                    b.Property<double>("TeacherStressRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("teacher_stress_rating");

                    b.Property<double>("TransportSpendingPerStudent")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("transport_spending_per_student");

                    b.Property<double>("WellbeingRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("wellbeing_rating");

                    b.HasKey("Id");

                    b.HasIndex("Ano");

                    b.HasIndex("SchoolInfoId", "Ano")
                        .IsUnique();

                    b.ToTable("school_rating", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolEnrollValues", b =>
                {
                    b.HasOne("Arkhos.Core.Models.SchoolEnrollDict", "SchoolEnrollDict")
                        .WithMany("SchoolEnrollValues")
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkhos.Core.Models.SchoolInfo", "SchoolInfo")
                        .WithMany("SchoolEnrollValues")
                        .HasForeignKey("IdEscolaEnrollValues", "Ano")
                        .HasPrincipalKey("IdEscola", "Ano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolEnrollDict");

                    b.Navigation("SchoolInfo");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfo", b =>
                {
                    b.HasOne("Arkhos.Core.Models.CityInfo", "CityInfo")
                        .WithMany("SchoolInfos")
                        .HasForeignKey("CityInfoId", "Ano")
                        .HasPrincipalKey("MunicipioId", "Ano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityInfo");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfraValues", b =>
                {
                    b.HasOne("Arkhos.Core.Models.SchoolInfraDict", "SchoolInfraDict")
                        .WithMany("SchoolInfraValues")
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkhos.Core.Models.SchoolInfo", "SchoolInfo")
                        .WithMany("SchoolInfraValues")
                        .HasForeignKey("IdEscolaInfraValues", "Ano")
                        .HasPrincipalKey("IdEscola", "Ano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolInfo");

                    b.Navigation("SchoolInfraDict");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolRating", b =>
                {
                    b.HasOne("Arkhos.Core.Models.SchoolInfo", "SchoolInfo")
                        .WithOne("SchoolRating")
                        .HasForeignKey("Arkhos.Core.Models.SchoolRating", "SchoolInfoId", "Ano")
                        .HasPrincipalKey("Arkhos.Core.Models.SchoolInfo", "IdEscola", "Ano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolInfo");
                });

            modelBuilder.Entity("Arkhos.Core.Models.CityInfo", b =>
                {
                    b.Navigation("SchoolInfos");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolEnrollDict", b =>
                {
                    b.Navigation("SchoolEnrollValues");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfo", b =>
                {
                    b.Navigation("SchoolEnrollValues");

                    b.Navigation("SchoolInfraValues");

                    b.Navigation("SchoolRating")
                        .IsRequired();
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfraDict", b =>
                {
                    b.Navigation("SchoolInfraValues");
                });
#pragma warning restore 612, 618
        }
    }
}
