// <auto-generated />
using Arkhos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arkhos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319014635_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arkhos.Core.Models.CityInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Ano")
                        .HasColumnType("bigint")
                        .HasColumnName("ano");

                    b.Property<long>("AreaTerritorial")
                        .HasColumnType("bigint")
                        .HasColumnName("area_territorial");

                    b.Property<double>("DensidadeDemografica")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("densidade_demografica");

                    b.Property<long>("IdMesorregiao")
                        .HasColumnType("bigint")
                        .HasColumnName("id_mesorregiao");

                    b.Property<long>("IdMicrorregiao")
                        .HasColumnType("bigint")
                        .HasColumnName("id_microrregiao");

                    b.Property<long>("MunicipioId")
                        .HasColumnType("bigint")
                        .HasColumnName("municipio_id");

                    b.Property<string>("NomeMesorregiao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_mesorregiao");

                    b.Property<string>("NomeMicrorregiao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_microrregiao");

                    b.Property<string>("NomeMunicipio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_municipio");

                    b.Property<long>("PopulacaoTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("populacao_total");

                    b.HasKey("Id");

                    b.ToTable("city_info", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Alocacao")
                        .HasColumnType("smallint")
                        .HasColumnName("alocacao");

                    b.Property<long>("Ano")
                        .HasColumnType("bigint")
                        .HasColumnName("ano");

                    b.Property<long>("CityInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_municipio_fk");

                    b.Property<short>("Dependencia")
                        .HasColumnType("smallint")
                        .HasColumnName("dependencia");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<short>("Funcionamento")
                        .HasColumnType("smallint")
                        .HasColumnName("funcionamento");

                    b.Property<long>("IdEscola")
                        .HasColumnType("bigint")
                        .HasColumnName("escola_id");

                    b.Property<short?>("Localizacao")
                        .HasColumnType("smallint");

                    b.Property<string>("NomeEscola")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_escola");

                    b.Property<short>("Ocupacao")
                        .HasColumnType("smallint")
                        .HasColumnName("ocupacao");

                    b.Property<int?>("Sede")
                        .HasColumnType("int")
                        .HasColumnName("sede");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("CityInfoId", "Ano");

                    b.ToTable("school_info", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), 1L, null, null, null, null, null);

                    b.Property<double>("AcessibilityRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("acessibility_rating");

                    b.Property<double>("AdministrativeBurdenRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("administrative_burden_rating");

                    b.Property<double>("AgeGradeDistortionRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("age_grade_distortion_rating");

                    b.Property<long>("Ano")
                        .HasColumnType("bigint")
                        .HasColumnName("ano");

                    b.Property<double?>("ApprovalRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("approval_rate");

                    b.Property<double?>("DropoutRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("dropout_rate");

                    b.Property<double?>("FailureRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("failure_rate");

                    b.Property<double>("HumanSupportRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("human_support_rating");

                    b.Property<double?>("IdebRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("ideb_rating");

                    b.Property<double>("InfrastructureSpendingPerStudent")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("infrastructure_spending_per_student");

                    b.Property<double>("ManagementRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("management_rating");

                    b.Property<double>("MealSpendingPerStudent")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("meal_spending_per_student");

                    b.Property<double>("PedagogicalRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("pedagogical_rating");

                    b.Property<double>("PedagogicalSpendingPerStudent")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("pedagogical_spending_per_student");

                    b.Property<double>("RecreationRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("recreation_rating");

                    b.Property<double?>("SaebRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("saeb_rating");

                    b.Property<long>("SchoolInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_escola_fk");

                    b.Property<double>("SpendingPerStudent")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("spending_per_student");

                    b.Property<double>("SpendingPerTeacher")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("spending_per_teacher");

                    b.Property<double>("TeacherInstabilityRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("teacher_instability_rating");

                    b.Property<double>("TeacherStressRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("teacher_stress_rating");

                    b.Property<double>("TransportSpendingPerStudent")
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("transport_spending_per_student");

                    b.Property<double>("WellbeingRating")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("wellbeing_rating");

                    b.HasKey("Id");

                    b.HasIndex("SchoolInfoId", "Ano")
                        .IsUnique();

                    b.ToTable("school_rating", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfo", b =>
                {
                    b.HasOne("Arkhos.Core.Models.CityInfo", "CityInfo")
                        .WithMany("SchoolInfos")
                        .HasForeignKey("CityInfoId", "Ano")
                        .HasPrincipalKey("MunicipioId", "Ano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityInfo");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolRating", b =>
                {
                    b.HasOne("Arkhos.Core.Models.SchoolInfo", "SchoolInfo")
                        .WithOne("SchoolRating")
                        .HasForeignKey("Arkhos.Core.Models.SchoolRating", "SchoolInfoId", "Ano")
                        .HasPrincipalKey("Arkhos.Core.Models.SchoolInfo", "IdEscola", "Ano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolInfo");
                });

            modelBuilder.Entity("Arkhos.Core.Models.CityInfo", b =>
                {
                    b.Navigation("SchoolInfos");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfo", b =>
                {
                    b.Navigation("SchoolRating")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
