// <auto-generated />
using System;
using Arkhos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arkhos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Arkhos.Core.Models.CityInfo", b =>
                {
                    b.Property<int>("MunicipioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("municipio_id");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ano");

                    b.Property<int>("AreaTerritorial")
                        .HasColumnType("REAL")
                        .HasColumnName("area_territorial");

                    b.Property<double>("DensidadeDemografica")
                        .HasColumnType("REAL")
                        .HasColumnName("densidade_demografica");

                    b.Property<int>("IdMesorregiao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_mesorregiao");

                    b.Property<int>("IdMicrorregiao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_microrregiao");

                    b.Property<string>("NomeMesorregiao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_mesorregiao");

                    b.Property<string>("NomeMicrorregiao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_microrregiao");

                    b.Property<string>("NomeMunicipio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_municipio");

                    b.Property<int>("PopulacaoTotal")
                        .HasColumnType("REAL")
                        .HasColumnName("populacao_total");

                    b.HasKey("MunicipioId", "Ano");

                    b.ToTable("city_info", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.CityTransparencyPortal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Credor")
                        .HasColumnType("TEXT")
                        .HasColumnName("credor");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("Detalhe")
                        .HasColumnType("TEXT")
                        .HasColumnName("detalhe");

                    b.Property<string>("Eixo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("eixo");

                    b.Property<string>("ElementoDespesa")
                        .HasColumnType("TEXT")
                        .HasColumnName("elemento_despesa");

                    b.Property<string>("Macro")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("macro");

                    b.Property<string>("Micro")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("micro");

                    b.Property<int>("MuncipioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("municipio_id_fk");

                    b.Property<int>("PortalOrigem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("portal_origem");

                    b.Property<double?>("Valor")
                        .HasColumnType("REAL")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("city_transparency_portal", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolEnrollDict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("grupo");

                    b.Property<int>("Tamanho")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tamanho");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<string>("Variavel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("variavel");

                    b.HasKey("Id");

                    b.ToTable("SchoolEnrollDicts");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolEnrollValues", b =>
                {
                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ano");

                    b.Property<int>("IdEscolaEnrollValues")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_escola_fk");

                    b.Property<int>("AtributoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_atributo");

                    b.Property<string>("TipoAtributo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_atributo");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL")
                        .HasColumnName("valor");

                    b.HasKey("Ano", "IdEscolaEnrollValues", "AtributoId");

                    b.HasIndex("AtributoId");

                    b.HasIndex("IdEscolaEnrollValues", "Ano");

                    b.ToTable("school_enroll_values", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfo", b =>
                {
                    b.Property<int>("IdEscola")
                        .HasColumnType("INTEGER")
                        .HasColumnName("escola_id");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ano");

                    b.Property<short>("Alocacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alocacao");

                    b.Property<int>("CityInfoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_municipio_fk");

                    b.Property<short>("Dependencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dependencia");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT")
                        .HasColumnName("endereco");

                    b.Property<short>("Funcionamento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("funcionamento");

                    b.Property<double?>("Lat")
                        .HasColumnType("REAL")
                        .HasColumnName("lat");

                    b.Property<short?>("Localizacao")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Lon")
                        .HasColumnType("REAL")
                        .HasColumnName("lon");

                    b.Property<string>("NomeEscola")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_escola");

                    b.Property<short>("Ocupacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ocupacao");

                    b.Property<int?>("Sede")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sede");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT")
                        .HasColumnName("telefone");

                    b.HasKey("IdEscola", "Ano");

                    b.HasIndex("CityInfoId", "Ano");

                    b.ToTable("school_info", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfraDict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("grupo");

                    b.Property<int>("Tamanho")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tamanho");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<string>("Variavel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("variavel");

                    b.HasKey("Id");

                    b.ToTable("school_infra_dict", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfraValues", b =>
                {
                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ano");

                    b.Property<int>("IdEscolaInfraValues")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_escola_fk");

                    b.Property<int>("AtributoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_atributo");

                    b.Property<string>("TipoAtributo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_atributo");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL")
                        .HasColumnName("valor");

                    b.HasKey("Ano", "IdEscolaInfraValues", "AtributoId");

                    b.HasIndex("AtributoId");

                    b.HasIndex("IdEscolaInfraValues", "Ano");

                    b.ToTable("school_infra_values", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolRating", b =>
                {
                    b.Property<int>("SchoolInfoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_escola_fk");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ano");

                    b.Property<double>("AcessibilityRating")
                        .HasColumnType("REAL")
                        .HasColumnName("acessibility_rating");

                    b.Property<double>("AdministrativeBurdenRating")
                        .HasColumnType("REAL")
                        .HasColumnName("administrative_burden_rating");

                    b.Property<double?>("AgeGradeDistortionRating")
                        .HasColumnType("REAL")
                        .HasColumnName("age_grade_distortion_rating");

                    b.Property<double?>("ApprovalRate")
                        .HasColumnType("REAL")
                        .HasColumnName("approval_rate");

                    b.Property<double?>("DropoutRate")
                        .HasColumnType("REAL")
                        .HasColumnName("dropout_rate");

                    b.Property<double?>("FailureRate")
                        .HasColumnType("REAL")
                        .HasColumnName("failure_rate");

                    b.Property<double?>("HumanSupportRating")
                        .HasColumnType("REAL")
                        .HasColumnName("human_support_rating");

                    b.Property<double?>("IdebRating")
                        .HasColumnType("REAL")
                        .HasColumnName("ideb_rating");

                    b.Property<double>("InfrastructureSpendingPerStudent")
                        .HasColumnType("REAL")
                        .HasColumnName("infrastructure_spending_per_student");

                    b.Property<double>("ManagementRating")
                        .HasColumnType("REAL")
                        .HasColumnName("management_rating");

                    b.Property<double>("MealSpendingPerStudent")
                        .HasColumnType("REAL")
                        .HasColumnName("meal_spending_per_student");

                    b.Property<double>("PedagogicalRating")
                        .HasColumnType("REAL")
                        .HasColumnName("pedagogical_rating");

                    b.Property<double>("PedagogicalSpendingPerStudent")
                        .HasColumnType("REAL")
                        .HasColumnName("pedagogical_spending_per_student");

                    b.Property<double>("RecreationRating")
                        .HasColumnType("REAL")
                        .HasColumnName("recreation_rating");

                    b.Property<double?>("SaebRating")
                        .HasColumnType("REAL")
                        .HasColumnName("saeb_rating");

                    b.Property<double>("SpendingPerStudent")
                        .HasColumnType("REAL")
                        .HasColumnName("spending_per_student");

                    b.Property<double>("SpendingPerTeacher")
                        .HasColumnType("REAL")
                        .HasColumnName("spending_per_teacher");

                    b.Property<double>("TeacherInstabilityRating")
                        .HasColumnType("REAL")
                        .HasColumnName("teacher_instability_rating");

                    b.Property<double>("TeacherStressRating")
                        .HasColumnType("REAL")
                        .HasColumnName("teacher_stress_rating");

                    b.Property<double>("TransportSpendingPerStudent")
                        .HasColumnType("REAL")
                        .HasColumnName("transport_spending_per_student");

                    b.Property<double>("WellbeingRating")
                        .HasColumnType("REAL")
                        .HasColumnName("wellbeing_rating");

                    b.HasKey("SchoolInfoId", "Ano");

                    b.HasIndex("Ano");

                    b.ToTable("school_rating", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.TargetInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ano");

                    b.Property<string>("Axis")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("axis");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<int>("IdAlvo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_alvo");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("level");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recomendacao");

                    b.Property<string>("TipoInsight")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_insight");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("titulo");

                    b.Property<double>("ValorBaseline")
                        .HasColumnType("REAL")
                        .HasColumnName("valor_baseline");

                    b.Property<string>("ValorDestaque")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("valor_destaque");

                    b.HasKey("Id");

                    b.ToTable("insights", (string)null);
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolEnrollValues", b =>
                {
                    b.HasOne("Arkhos.Core.Models.SchoolEnrollDict", "SchoolEnrollDict")
                        .WithMany("SchoolEnrollValues")
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkhos.Core.Models.SchoolInfo", "SchoolInfo")
                        .WithMany("SchoolEnrollValues")
                        .HasForeignKey("IdEscolaEnrollValues", "Ano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolEnrollDict");

                    b.Navigation("SchoolInfo");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfo", b =>
                {
                    b.HasOne("Arkhos.Core.Models.CityInfo", "CityInfo")
                        .WithMany("SchoolInfos")
                        .HasForeignKey("CityInfoId", "Ano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityInfo");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfraValues", b =>
                {
                    b.HasOne("Arkhos.Core.Models.SchoolInfraDict", "SchoolInfraDict")
                        .WithMany("SchoolInfraValues")
                        .HasForeignKey("AtributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkhos.Core.Models.SchoolInfo", "SchoolInfo")
                        .WithMany("SchoolInfraValues")
                        .HasForeignKey("IdEscolaInfraValues", "Ano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolInfo");

                    b.Navigation("SchoolInfraDict");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolRating", b =>
                {
                    b.HasOne("Arkhos.Core.Models.SchoolInfo", "SchoolInfo")
                        .WithOne("SchoolRating")
                        .HasForeignKey("Arkhos.Core.Models.SchoolRating", "SchoolInfoId", "Ano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolInfo");
                });

            modelBuilder.Entity("Arkhos.Core.Models.CityInfo", b =>
                {
                    b.Navigation("SchoolInfos");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolEnrollDict", b =>
                {
                    b.Navigation("SchoolEnrollValues");
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfo", b =>
                {
                    b.Navigation("SchoolEnrollValues");

                    b.Navigation("SchoolInfraValues");

                    b.Navigation("SchoolRating")
                        .IsRequired();
                });

            modelBuilder.Entity("Arkhos.Core.Models.SchoolInfraDict", b =>
                {
                    b.Navigation("SchoolInfraValues");
                });
#pragma warning restore 612, 618
        }
    }
}
